version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: aegisai_postgres
    environment:
      POSTGRES_DB: aegisai_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    container_name: aegisai_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: aegisai_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  mongo_data:
